let appState={selectedTrain:null,selectedSeats:[],passengers:[],searchDate:'',searchTime:'',selectedClass:'standard',admin:null};
const $=id=>document.getElementById(id);const naira=n=>`₦${Number(n||0).toLocaleString('en-NG')}`;
document.addEventListener('DOMContentLoaded',()=>{initNavigation();populateStations();bindForms();bindPasswordToggles();updateUI();advanceBookingStatuses();setInterval(()=>{advanceBookingStatuses();if(getCurrentUserSession())renderBookings();},30000);});
function initNavigation(){document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.nav)));$('nav-hamburger-btn')?.addEventListener('click',()=>{$('main-nav-links')?.classList.toggle('open');});}
function showView(view){document.querySelectorAll('.view-section').forEach(v=>v.style.display='none');const map={search:'search-results-view',bookings:'bookings-view',report:'report-view',guide:'guide-view',admin:'admin-view',wallet:'wallet-view',live:'live-tracker-view'};const target=$(map[view]||'search-results-view');if(target)target.style.display='block';if(view==='bookings')renderBookings();if(view==='report')renderReports();if(view==='admin')renderAdmin();if(view==='guide')renderStations();if(view==='wallet')renderWallet();if(view==='live')initLiveTrackerUI();}
function populateStations(){const o=$('select-origin'),d=$('select-destination');if(!o||!d)return;const opts='<option value="">Select station</option>'+STATIONS.map(s=>`<option value="${s.id}">${s.name} — ${s.city}</option>`).join('');o.innerHTML=opts;d.innerHTML=opts;}
function bindForms(){$('search-trains-form')?.addEventListener('submit',e=>{e.preventDefault();searchTrains();});$('btn-one-way')?.addEventListener('click',()=>setTrip(false));$('btn-round-trip')?.addEventListener('click',()=>setTrip(true));$('confirm-booking-btn')?.addEventListener('click',confirmBooking);$('report-form')?.addEventListener('submit',submitReport);$('admin-schedule-form')?.addEventListener('submit',adminSchedule);$('admin-report-filter')?.addEventListener('change',renderAdminReports);$('wallet-topup-btn')?.addEventListener('click',topUpWallet);$('apply-promo-btn')?.addEventListener('click',applyPromo);$('btn-back-to-search')?.addEventListener('click',()=>showView('search'));}
function setTrip(round){$('btn-one-way')?.classList.toggle('active',!round);$('btn-round-trip')?.classList.toggle('active',round);$('group-return-date').style.display=round?'block':'none';}
function searchTrains(){const o=$('select-origin').value,d=$('select-destination').value;if(!o||!d||o===d)return alert('Please select different departure and arrival stations.');appState.searchDate=$('input-dep-date').value;appState.searchTime=$('input-dep-time').value;appState.selectedClass=$('select-class').value;let schedules=[...TRAIN_SCHEDULES,...getCustomSchedules()];if(appState.searchDate){const day=new Date(appState.searchDate+'T12:00:00').toLocaleDateString('en-US',{weekday:'short'});schedules=schedules.filter(t=>t.origin===o&&t.destination===d&&(t.operatingDays||[]).includes(day));}else schedules=schedules.filter(t=>t.origin===o&&t.destination===d);if(appState.searchTime)schedules=schedules.filter(t=>t.departureTime>=appState.searchTime);renderSchedules(schedules);showView('search');}
function renderSchedules(list){const box=$('schedules-list-container');$('results-count-badge').textContent=`${list.length} Trains Found`;if(!list.length){box.innerHTML='<div class="empty-state">No train schedule is available for this route/date/time.</div>';return;}box.innerHTML=list.map(t=>{const from=STATIONS.find(s=>s.id===t.origin),to=STATIONS.find(s=>s.id===t.destination);return`<div class="schedule-card"><div><strong>${t.trainNumber}</strong><p>${from?.name||t.origin} → ${to?.name||t.destination}</p><small>${t.departureTime} — ${t.arrivalTime} · ${t.duration||''}</small><br><small>Runs: ${(t.operatingDays||[]).join(', ')}</small></div><div><strong>${naira(t.baseFare)}</strong><br><button class="btn btn-primary" onclick="startBooking('${t.id}')">Select Seats & Book</button></div></div>`;}).join('');}
function findTrain(id){return[...TRAIN_SCHEDULES,...getCustomSchedules()].find(t=>t.id===id);}
function startBooking(id){const user=getCurrentUserSession();if(!user){openAuth();return;}if(!appState.searchDate){alert('Please select a travel date before booking.');return;}const t=findTrain(id);if(!t)return;appState.selectedTrain=t;appState.selectedSeats=[];showView('seat');$('seat-selection-view').style.display='block';$('search-results-view').style.display='none';$('summary-train-details').innerHTML=`<strong>${t.trainNumber}</strong><p>${t.departureTime} → ${t.arrivalTime}</p><p>${appState.searchDate}</p>`;renderSeatMap('seat-map-wrapper',t,appState.searchDate,appState.selectedClass,s=>{appState.selectedSeats=s;updateSummary();});renderPassengerInputs();updateSummary();}
function renderPassengerInputs(){const n=Number($('select-passengers').value||1);$('passenger-inputs-container').innerHTML=Array.from({length:n},(_,i)=>`<div class="passenger-row"><h5>Passenger ${i+1}</h5><div class="two-col"><input class="form-control pax-name" placeholder="Full name" required><input class="form-control pax-nin" maxlength="11" placeholder="NIN (11 digits)" required></div></div>`).join('');}
function updateSummary(){const t=appState.selectedTrain;if(!t)return;const count=Number($('select-passengers').value||1),cls=TRAVEL_CLASSES.find(c=>c.id===appState.selectedClass)||TRAVEL_CLASSES[0],addons=[...document.querySelectorAll('#add-ons-container input:checked')].reduce((s,x)=>s+Number(x.dataset.price||0),0),base=t.baseFare*count*cls.multiplier,total=base+addons;$('sum-p-count').textContent=count;$('sum-base-fare').textContent=naira(t.baseFare*count);$('sum-class-multiplier').textContent=cls.multiplier+'x';$('sum-addons-cost').textContent=naira(addons);$('sum-total-payable').textContent=naira(total);$('wallet-checkout-balance').textContent=getCurrentUserSession()?`Balance: ${naira(getWalletBalance())}`:'';}
function confirmBooking(){const u=getCurrentUserSession(),t=appState.selectedTrain;if(!u||!t)return openAuth();if(!appState.searchDate)return alert('Travel date is required for booking.');if(!appState.selectedSeats.length)return alert('Select at least one seat.');const pax=[...document.querySelectorAll('.pax-name')].map((x,i)=>({fullName:x.value,nin:document.querySelectorAll('.pax-nin')[i]?.value||''}));if(pax.some(p=>!p.fullName||p.nin.length!==11))return alert('Complete passenger details and valid 11-digit NIN.');const cls=TRAVEL_CLASSES.find(c=>c.id===appState.selectedClass)||TRAVEL_CLASSES[0];const addons=[...document.querySelectorAll('#add-ons-container input:checked')].reduce((s,x)=>s+Number(x.dataset.price||0),0);let total=t.baseFare*pax.length*cls.multiplier+addons;const promo=$('promo-code-input')?.value.trim().toUpperCase();if(PROMO_CODES[promo])total*=1-PROMO_CODES[promo].discountPercent/100;const bal=getWalletBalance(u.id);if(bal<total)return alert(`Insufficient wallet balance. Required ${naira(total)}.`);const newBal=bal-total;setWalletBalance(newBal,u.id);const now=new Date().toISOString(),booking={id:'BKG-'+Date.now(),pnr:createBookingReference(),userId:u.id,userEmail:u.email,userName:u.fullName,trainId:t.id,trainNumber:t.trainNumber,origin:t.origin,destination:t.destination,travelDate:appState.searchDate,departureDateTime:`${appState.searchDate}T${t.departureTime}`,departureTime:t.departureTime,arrivalTime:t.arrivalTime,selectedSeats:appState.selectedSeats,totalPrice:Math.round(total),passengers:pax,status:'Confirmed',createdAt:now,statusHistory:[{status:'Confirmed',at:now,by:'Passenger'}]};saveBooking(booking);addWalletTransaction(u.id,'debit',total,`Train booking ${booking.pnr}`,booking.pnr,newBal);alert(`Booking confirmed: ${booking.pnr}`);showView('bookings');updateUI();}
function renderPassengerAddons(){if(!$('add-ons-container'))return;$('add-ons-container').innerHTML=ADD_ONS.map(a=>`<label class="addon-option"><input type="checkbox" data-price="${a.price}" onchange="updateSummary()"> ${a.icon} ${a.name} (${naira(a.price)})</label>`).join('');}
function applyPromo(){const code=$('promo-code-input').value.trim().toUpperCase();const p=PROMO_CODES[code];$('promo-msg').textContent=p?`${p.description} applied.`:'Invalid promo code.';updateSummary();}
function renderBookings(){const u=getCurrentUserSession(),box=$('my-bookings-container');if(!u){box.innerHTML='<div class="empty-state">Please sign in to view your bookings.</div>';return;}const bs=getBookings().filter(b=>b.userId===u.id);if(!bs.length){box.innerHTML='<div class="empty-state">You have no bookings yet.</div>';return;}box.innerHTML=bs.map(b=>`<div class="booking-card"><div><strong>${b.pnr}</strong><p>${b.trainNumber}</p><p>${b.travelDate} · ${b.departureTime} · Seats: ${b.selectedSeats.join(', ')}</p><span class="status-badge status-${b.status.toLowerCase().replace(' ','-')}">${b.status}</span></div><div><strong>${naira(b.totalPrice)}</strong>${b.status==='Confirmed'?`<br><button class="btn btn-sm btn-danger" onclick="cancelMyBooking('${b.id}')">Cancel</button>`:''}</div></div>`).join('');}
function cancelMyBooking(id){const r=cancelBooking(id);if(r.success){alert(`Cancelled. Refund: ${naira(r.refundAmount)}`);renderBookings();updateUI();}else alert(r.message);}
function submitReport(e){e.preventDefault();const u=getCurrentUserSession();if(!u)return openAuth();const r={id:'RPT-'+Date.now(),userId:u.id,userName:u.fullName,type:$('report-type').value,bookingId:$('report-booking').value,subject:$('report-subject').value,description:$('report-description').value,status:'Open',createdAt:new Date().toISOString()};saveReport(r);e.target.reset();$('report-form-msg').textContent='Report submitted successfully.';renderReports();}
function renderReports(){const u=getCurrentUserSession();const box=$('user-reports-list');if(!u){box.innerHTML='<div class="empty-state">Sign in to submit and view reports.</div>';return;}const rs=getUserReports(u.id);box.innerHTML=rs.length?rs.map(r=>`<div class="report-card"><strong>${r.subject}</strong><p>${r.description}</p><small>${r.type} · ${r.createdAt.slice(0,10)}</small><br><span class="status-badge">${r.status}</span>${r.adminResponse?`<p><strong>Admin:</strong> ${r.adminResponse}</p>`:''}</div>`).join(''):'<div class="empty-state">No reports submitted.</div>';const sel=$('report-booking');if(sel)sel.innerHTML='<option value="">General issue</option>'+getBookings().filter(b=>b.userId===u.id).map(b=>`<option value="${b.id}">${b.pnr} — ${b.trainNumber}</option>`).join('');}
function renderWallet(){const u=getCurrentUserSession();$('wallet-page-balance').textContent=u?naira(getWalletBalance(u.id)):'₦0';const box=$('wallet-transactions-list');if(!u){box.innerHTML='<div class="empty-state">Sign in to view your wallet.</div>';return;}const tx=getWalletTransactions(u.id);box.innerHTML=tx.length?tx.map(t=>`<div class="transaction-row"><div><strong>${t.type==='credit'?'+':'-'} ${naira(t.amount)}</strong><p>${t.description}</p><small>${new Date(t.createdAt).toLocaleString()}</small></div><span>${naira(t.balanceAfter)}</span></div>`).join(''):'<div class="empty-state">No transactions yet.</div>';}
function topUpWallet(){const u=getCurrentUserSession();if(!u)return openAuth();const n=Number(prompt('Enter top-up amount (₦):'));if(!Number.isFinite(n)||n<=0)return;const b=getWalletBalance(u.id)+n;setWalletBalance(b,u.id);addWalletTransaction(u.id,'credit',n,'E-Wallet top-up','TOP-'+Date.now(),b);renderWallet();updateUI();}
function renderStations(){$('stations-guide-container').innerHTML=STATIONS.map(s=>`<div class="station-card"><strong>${s.name}</strong><p>${s.city}, ${s.state} · ${s.code}</p></div>`).join('');}
function renderAdmin(){const admin=appState.admin;if(!admin){$('admin-view').innerHTML='<div class="search-card"><h3>Admin Login</h3><input id="admin-id" class="form-control" placeholder="Staff ID"><input id="admin-pass" type="password" class="form-control" placeholder="Passcode"><button class="btn btn-primary" onclick="adminLogin()">Sign In</button><small>Demo: ADMIN-SW-01 / lagos-station</small></div>';return;}const bs=getBookings(),users=getRegisteredUsers(),rs=getReports();$('admin-dashboard-cards').innerHTML=[['Bookings',bs.length],['Confirmed',bs.filter(b=>b.status==='Confirmed').length],['Completed',bs.filter(b=>b.status==='Completed').length],['Cancelled',bs.filter(b=>b.status==='Cancelled').length],['Open Reports',rs.filter(r=>r.status==='Open').length],['Passengers',users.length]].map(x=>`<div class="admin-stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('admin-bookings-list').innerHTML=bs.map(b=>`<div class="admin-list-row"><span>${b.pnr}<br><small>${b.userEmail}</small></span><select onchange="adminBookingStatus('${b.id}',this.value)"><option ${b.status==='Confirmed'?'selected':''}>Confirmed</option><option ${b.status==='Completed'?'selected':''}>Completed</option><option ${b.status==='Cancelled'?'selected':''}>Cancelled</option></select></div>`).join('')||'<p>No bookings.</p>';$('admin-users-list').innerHTML=users.map(u=>`<div class="admin-list-row"><span>${u.fullName}<br><small>${u.email}</small></span><span>${bs.filter(b=>b.userId===u.id).length} bookings</span></div>`).join('');$('zonal-trains-list').innerHTML=[...TRAIN_SCHEDULES,...getCustomSchedules()].map(t=>`<div class="admin-list-row"><span>${t.trainNumber}<br><small>${t.origin} → ${t.destination}</small></span><span>${t.departureTime}</span></div>`).join('');renderAdminReports();}
function adminLogin(){const id=$('admin-id').value.trim(),pass=$('admin-pass').value,admin=ZONAL_ADMIN_ACCOUNTS.find(a=>a.staffId===id&&a.passcode===pass);if(!admin)return alert('Invalid admin credentials.');appState.admin=admin;renderAdmin();}
function adminBookingStatus(id,status){const a=getBookings(),i=a.findIndex(b=>b.id===id);if(i<0)return;const b=a[i];if(b.status===status)return;if(status==='Cancelled'&&b.status!=='Cancelled'){const r=cancelBooking(id);if(!r.success)return alert(r.message);}else{b.status=status;b.statusHistory=Array.isArray(b.statusHistory)?b.statusHistory:[];b.statusHistory.push({status,at:new Date().toISOString(),by:'Admin'});localStorage.setItem(STORAGE_KEYS.BOOKINGS,JSON.stringify(a));}renderAdmin();}
function adminSchedule(e){e.preventDefault();const s={id:'ADM-'+Date.now(),trainNumber:$('admin-train-name').value,origin:$('admin-origin').value,destination:$('admin-destination').value,operatingDays:$('admin-days').value.split(',').map(x=>x.trim()).filter(Boolean),departureTime:$('admin-dep-time').value,arrivalTime:$('admin-arr-time').value,baseFare:Number($('admin-fare').value),duration:'Scheduled',coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]};saveCustomSchedule(s);e.target.reset();renderAdmin();}
function renderAdminReports(){const f=$('admin-report-filter')?.value||'all',box=$('admin-reports-list');if(!box)return;let rs=getReports();if(f!=='all')rs=rs.filter(r=>r.status===f);box.innerHTML=rs.length?rs.map(r=>`<div class="report-card"><strong>${r.subject}</strong><p>${r.description}</p><small>${r.userName} · ${r.type}</small><div class="two-col"><select id="rstatus-${r.id}" class="form-control"><option ${r.status==='Open'?'selected':''}>Open</option><option ${r.status==='In Progress'?'selected':''}>In Progress</option><option ${r.status==='Resolved'?'selected':''}>Resolved</option></select><input id="rresponse-${r.id}" class="form-control" placeholder="Admin response" value="${(r.adminResponse||'').replaceAll('"','&quot;')}"></div><button class="btn btn-primary btn-sm" onclick="saveAdminReport('${r.id}')">Save Resolution</button></div>`).join(''):'<p>No reports.</p>';}
function saveAdminReport(id){updateReport(id,{status:$(`rstatus-${id}`).value,adminResponse:$(`rresponse-${id}`).value,resolvedAt:$(`rstatus-${id}`).value==='Resolved'?new Date().toISOString():null});renderAdminReports();}
function updateUI(){const u=getCurrentUserSession();$('user-account-widget').innerHTML=u?`<button class="account-btn" onclick="openProfile()">${u.fullName}</button><button class="account-btn" onclick="logout()">Logout</button>`:`<button class="account-btn" onclick="openAuth()">Sign In / Create Account</button>`;$('wallet-display').innerHTML=u?`E-Wallet: <strong>${naira(getWalletBalance(u.id))}</strong>`:'E-Wallet: <strong>Sign in</strong>';if($('my-bookings-nav'))$('my-bookings-nav').style.display=u?'inline-flex':'none';if($('report-nav'))$('report-nav').style.display=u?'inline-flex':'none';renderWallet();renderPassengerAddons();}
function openAuth(){if($('user-auth-modal'))$('user-auth-modal').style.display='flex';}
function closeAuth(){if($('user-auth-modal'))$('user-auth-modal').style.display='none';}
function bindPasswordToggles(){document.querySelectorAll('.password-toggle').forEach(b=>b.addEventListener('click',()=>{const i=$(b.dataset.togglePassword);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁':'🙈';}));$('btn-close-user-auth')?.addEventListener('click',closeAuth);$('tab-user-login')?.addEventListener('click',()=>{ $('user-login-view').style.display='block';$('user-register-view').style.display='none';});$('tab-user-register')?.addEventListener('click',()=>{$('user-login-view').style.display='none';$('user-register-view').style.display='block';});$('user-login-form')?.addEventListener('submit',e=>{e.preventDefault();const r=authenticateUser($('user-login-email').value,$('user-login-password').value);if(!r.success)return $('user-login-error').textContent=r.message;closeAuth();updateUI();});$('user-register-form')?.addEventListener('submit',e=>{e.preventDefault();const r=registerUser({fullName:$('user-reg-name').value,email:$('user-reg-email').value,phone:$('user-reg-phone').value,nin:$('user-reg-nin').value,password:$('user-reg-password').value});if(!r.success)return $('user-register-error').textContent=r.message;closeAuth();updateUI();});}
function quickFillUserLogin(email,password){$('user-login-email').value=email;$('user-login-password').value=password;}
function logout(){logoutUserSession();appState.admin=null;updateUI();showView('search');}
function openProfile(){const u=getCurrentUserSession();if(!u)return;['name','email','phone','nin'].forEach(x=>{const el=$('profile-'+x);if(el)el.value=x==='name'?u.fullName:x==='email'?u.email:x==='phone'?u.phone:u.nin;});$('user-profile-modal').style.display='flex';}
function closeUserProfileModal(){$('user-profile-modal').style.display='none';}
function saveProfileChanges(e){e.preventDefault();const u=getCurrentUserSession(),users=getRegisteredUsers(),i=users.findIndex(x=>x.id===u.id);if(i<0)return;users[i].fullName=$('profile-name').value;users[i].phone=$('profile-phone').value;if($('profile-password').value)users[i].password=$('profile-password').value;localStorage.setItem(STORAGE_KEYS.USERS,JSON.stringify(users));setCurrentUserSession(users[i]);$('profile-save-msg').textContent='Profile saved.';updateUI();}
function deleteUserAccount(){const u=getCurrentUserSession();if(!u||!confirm('Delete your account?'))return;localStorage.setItem(STORAGE_KEYS.USERS,JSON.stringify(getRegisteredUsers().filter(x=>x.id!==u.id)));logout();closeUserProfileModal();}
window.startBooking=startBooking;window.cancelMyBooking=cancelMyBooking;window.quickFillUserLogin=quickFillUserLogin;window.openProfile=openProfile;window.closeUserProfileModal=closeUserProfileModal;window.saveProfileChanges=saveProfileChanges;window.deleteUserAccount=deleteUserAccount;window.adminLogin=adminLogin;window.adminBookingStatus=adminBookingStatus;window.saveAdminReport=saveAdminReport;window.updateSummary=updateSummary;
