const STATIONS=[{id:'LOS_MJ',code:'MJ-LOS',name:'Mobolaji Johnson Station',city:'Ebute Metta, Lagos',state:'Lagos'},{id:'LOS_AGE',code:'BF-AGE',name:'Babatunde Fashola Station',city:'Agege, Lagos',state:'Lagos'},{id:'OGN_ABK',code:'WS-ABK',name:'Wole Soyinka Station',city:'Lula / Abeokuta',state:'Ogun'},{id:'OYO_IBD',code:'SLA-IBD',name:'Chief Samuel Ladoke Akintola Station',city:'Moniya, Ibadan',state:'Oyo'},{id:'FCT_IDU',code:'IDU-ABJ',name:'Idu Railway Station',city:'Idu, Abuja',state:'FCT Abuja'},{id:'KAD_RIG',code:'RIG-KAD',name:'Rigasa Station',city:'Rigasa, Kaduna',state:'Kaduna'},{id:'DEL_WAR',code:'UJV-WAR',name:'Ujevwu Station',city:'Warri',state:'Delta'},{id:'KOG_ITK',code:'ITK-KOG',name:'Itakpe Central Station',city:'Itakpe',state:'Kogi'}];
const TRAVEL_CLASSES=[{id:'standard',name:'Standard Coach',multiplier:1,icon:'🚆',description:'Comfortable seating with overhead luggage racks'},{id:'first',name:'First Class',multiplier:1.5,icon:'⭐',description:'Air-conditioned, wide recliners & charging outlets'},{id:'executive',name:'Executive Suite',multiplier:2.2,icon:'👑',description:'VIP lounge access, complimentary meal & ultra-spacious seats'}];
const TRAIN_SCHEDULES=[
{id:'TR-101',trainNumber:'NRC-Kajola Express (101)',origin:'LOS_MJ',destination:'OYO_IBD',departureTime:'08:00',arrivalTime:'10:30',duration:'2h 30m',baseFare:3600,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-102',trainNumber:'NRC-Lag-Ibd Bullet (102)',origin:'LOS_MJ',destination:'OYO_IBD',departureTime:'12:30',arrivalTime:'14:45',duration:'2h 15m',baseFare:4000,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-103',trainNumber:'NRC-Night Commuter (103)',origin:'LOS_MJ',destination:'OYO_IBD',departureTime:'16:00',arrivalTime:'18:30',duration:'2h 30m',baseFare:3600,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-104',trainNumber:'NRC-Ibadan Morning Shuttle (104)',origin:'OYO_IBD',destination:'LOS_MJ',departureTime:'08:00',arrivalTime:'10:30',duration:'2h 30m',baseFare:3600,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-105',trainNumber:'NRC-Abeokuta Express (105)',origin:'OYO_IBD',destination:'LOS_MJ',departureTime:'16:30',arrivalTime:'19:00',duration:'2h 30m',baseFare:3600,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-201',trainNumber:'NRC-Capital Express (201)',origin:'FCT_IDU',destination:'KAD_RIG',departureTime:'09:45',arrivalTime:'12:00',duration:'2h 15m',baseFare:5000,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-202',trainNumber:'NRC-Northern Shuttle (202)',origin:'KAD_RIG',destination:'FCT_IDU',departureTime:'14:00',arrivalTime:'16:15',duration:'2h 15m',baseFare:5000,operatingDays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]},
{id:'TR-301',trainNumber:'NRC-Delta Link (301)',origin:'DEL_WAR',destination:'KOG_ITK',departureTime:'07:30',arrivalTime:'12:30',duration:'5h 00m',baseFare:4500,operatingDays:['Mon','Wed','Fri','Sun'],coaches:[{coachNo:1,type:'standard',totalSeats:40},{coachNo:2,type:'first',totalSeats:24},{coachNo:3,type:'executive',totalSeats:16}]}];
const DEMO_NIN_DATABASE={'12345678901':{fullName:'Adam Babatunde',dob:'1998-05-14',gender:'Male',state:'Lagos'},'98765432109':{fullName:'Amina Zainab Bello',dob:'2001-11-20',gender:'Female',state:'Kaduna'}};
const ADD_ONS=[{id:'extra_baggage',name:'Extra Luggage (up to 30kg)',price:1500,icon:'🧳'},{id:'hot_meal',name:'Jollof Rice & Chicken Meal Pack',price:2500,icon:'🍱'},{id:'vip_lounge',name:'VIP Station Lounge Access',price:3000,icon:'🛋️'},{id:'sms_alerts',name:'Instant Travel SMS & Track Alerts',price:500,icon:'📱'}];
const PROMO_CODES={'STUDENT2026':{discountPercent:15,description:'15% CS Student Discount'},'NAIJARAILES':{discountPercent:10,description:'10% Launch Promo'},'NRCVIP':{discountPercent:20,description:'20% Executive Partner Discount'}};
const ADMIN_ZONES=[{id:'SW_ZONE',name:'South-West Zone Admin (Lagos / Ibadan District)',officer:'Engr. O. Adebayo',assignedStations:['LOS_MJ','LOS_AGE','OGN_ABK','OYO_IBD']},{id:'NC_ZONE',name:'Northern Zone Admin (Abuja / Kaduna District)',officer:'Hajia F. Usman',assignedStations:['FCT_IDU','KAD_RIG']},{id:'SS_ZONE',name:'South-South Zone Admin (Warri / Itakpe District)',officer:'Mr. E. Okon',assignedStations:['DEL_WAR','KOG_ITK']}];
const ZONAL_ADMIN_ACCOUNTS=[{staffId:'ADMIN-SW-01',passcode:'lagos-station',zoneId:'SW_ZONE',zoneName:'South-West Zone (Lagos / Ibadan District)',officerName:'Engr. O. Adebayo',title:'Lagos District Station Master',assignedStations:['LOS_MJ','LOS_AGE','OGN_ABK','OYO_IBD']},{staffId:'ADMIN-NC-02',passcode:'abuja-station',zoneId:'NC_ZONE',zoneName:'Northern Zone (Abuja / Kaduna District)',officerName:'Hajia F. Usman',title:'Abuja District Station Master',assignedStations:['FCT_IDU','KAD_RIG']},{staffId:'ADMIN-SS-03',passcode:'warri-station',zoneId:'SS_ZONE',zoneName:'South-South Zone (Warri / Itakpe District)',officerName:'Mr. E. Okon',title:'Warri District Station Master',assignedStations:['DEL_WAR','KOG_ITK']}];
