const STORAGE_KEYS={BOOKINGS:'nrc_bookings_v1',SEAT_OCCUPANCY:'nrc_seat_occupancy_v1',WALLET_BALANCE:'nrc_wallet_balance_v1',CUSTOM_SCHEDULES:'nrc_custom_schedules_v1',USERS:'nrc_registered_users_v1',CURRENT_USER:'nrc_current_user_v1',REPORTS:'nrc_reports_v1',WALLET_TRANSACTIONS:'nrc_wallet_transactions_v1'};
function getWalletStore(){const d=localStorage.getItem(STORAGE_KEYS.WALLET_BALANCE);if(!d)return{};try{const p=JSON.parse(d);if(p&&typeof p==='object'&&!Array.isArray(p))return p;}catch(e){}return{};}
function getWalletUserId(userId=null){if(userId)return userId;const u=typeof getCurrentUserSession==='function'?getCurrentUserSession():null;return u?u.id:null;}
function getWalletBalance(userId=null){const id=getWalletUserId(userId);if(!id)return 0;const raw=localStorage.getItem(STORAGE_KEYS.WALLET_BALANCE);if(raw!==null){try{const p=JSON.parse(raw);if(typeof p==='number'){const b=Number.isFinite(p)?p:15000;localStorage.setItem(STORAGE_KEYS.WALLET_BALANCE,JSON.stringify({[id]:b}));return b;}}catch(e){const b=parseFloat(raw);if(!Number.isNaN(b)){localStorage.setItem(STORAGE_KEYS.WALLET_BALANCE,JSON.stringify({[id]:b}));return b;}}}const s=getWalletStore();if(Object.prototype.hasOwnProperty.call(s,id)){const b=parseFloat(s[id]);return Number.isFinite(b)?b:0;}s[id]=15000;localStorage.setItem(STORAGE_KEYS.WALLET_BALANCE,JSON.stringify(s));return 15000;}
function setWalletBalance(amount,userId=null){const id=getWalletUserId(userId);if(!id)return;const s=getWalletStore();const n=Number(amount);s[id]=Number.isFinite(n)?Math.max(0,n):0;localStorage.setItem(STORAGE_KEYS.WALLET_BALANCE,JSON.stringify(s));}
function getWalletTransactions(userId=null){const id=getWalletUserId(userId);if(!id)return[];try{const a=JSON.parse(localStorage.getItem(STORAGE_KEYS.WALLET_TRANSACTIONS)||'[]');return Array.isArray(a)?a.filter(t=>t.userId===id):[];}catch(e){return[];}}
function saveWalletTransaction(t){if(!t?.userId)return null;let a=[];try{a=JSON.parse(localStorage.getItem(STORAGE_KEYS.WALLET_TRANSACTIONS)||'[]');}catch(e){}const tx={id:t.id||'TX-'+Date.now(),userId:t.userId,type:t.type,amount:Number(t.amount)||0,description:t.description||'',reference:t.reference||'',balanceAfter:Number(t.balanceAfter)||0,createdAt:t.createdAt||new Date().toISOString()};a.unshift(tx);localStorage.setItem(STORAGE_KEYS.WALLET_TRANSACTIONS,JSON.stringify(a));return tx;}
function addWalletTransaction(userId,type,amount,description,reference,balanceAfter){return saveWalletTransaction({userId,type,amount,description,reference,balanceAfter});}
function getBookings(){const d=localStorage.getItem(STORAGE_KEYS.BOOKINGS);return d?JSON.parse(d):[];}
function saveBooking(b){const a=getBookings();a.unshift(b);localStorage.setItem(STORAGE_KEYS.BOOKINGS,JSON.stringify(a));markSeatsOccupied(b.trainId,b.travelDate,b.selectedSeats);}
function cancelBooking(id){const a=getBookings(),i=a.findIndex(b=>b.id===id);if(i<0)return{success:false,message:'Booking reference not found.'};const b=a[i];if(b.status==='Cancelled')return{success:false,message:'This ticket has already been cancelled.'};b.status='Cancelled';b.cancelledAt=new Date().toISOString();b.statusHistory=Array.isArray(b.statusHistory)?b.statusHistory:[];b.statusHistory.push({status:'Cancelled',at:b.cancelledAt,by:'Passenger'});a[i]=b;localStorage.setItem(STORAGE_KEYS.BOOKINGS,JSON.stringify(a));unmarkSeatsOccupied(b.trainId,b.travelDate,b.selectedSeats);const refund=b.totalPrice*.9,uid=b.userId||(getCurrentUserSession()?.id||null),bal=getWalletBalance(uid),nb=bal+refund;setWalletBalance(nb,uid);addWalletTransaction(uid,'credit',refund,`90% refund for cancelled booking ${b.pnr||b.id}`,b.pnr||b.id,nb);return{success:true,refundAmount:refund,newBalance:nb};}
function getOccupancyKey(t,d){return`${STORAGE_KEYS.SEAT_OCCUPANCY}_${t}_${d}`;}
function getOccupiedSeats(t,d){const k=getOccupancyKey(t,d),x=localStorage.getItem(k);if(x)return JSON.parse(x);const m=['1-A3','1-B2','1-C4','2-A1','2-B4','3-A2'];localStorage.setItem(k,JSON.stringify(m));return m;}
function markSeatsOccupied(t,d,s){const a=getOccupiedSeats(t,d);localStorage.setItem(getOccupancyKey(t,d),JSON.stringify(Array.from(new Set([...a,...s]))));}
function unmarkSeatsOccupied(t,d,s){localStorage.setItem(getOccupancyKey(t,d),JSON.stringify(getOccupiedSeats(t,d).filter(x=>!s.includes(x))));}
function getCustomSchedules(){const d=localStorage.getItem(STORAGE_KEYS.CUSTOM_SCHEDULES);return d?JSON.parse(d):[];}
function saveCustomSchedule(s){const a=getCustomSchedules();a.push(s);localStorage.setItem(STORAGE_KEYS.CUSTOM_SCHEDULES,JSON.stringify(a));}
function getRegisteredUsers(){const d=localStorage.getItem(STORAGE_KEYS.USERS);if(d)return JSON.parse(d);const a=[{id:'USR-01',fullName:'Adam Babatunde',email:'adam@nrc.ng',password:'password123',phone:'+2348012345678',nin:'12345678901',createdAt:new Date().toISOString()}];localStorage.setItem(STORAGE_KEYS.USERS,JSON.stringify(a));return a;}
function registerUser(x){const a=getRegisteredUsers();if(a.find(u=>u.email.toLowerCase()===x.email.toLowerCase()))return{success:false,message:'An account with this email address already exists.'};const u={id:'USR-'+Date.now(),fullName:x.fullName,email:x.email,password:x.password,phone:x.phone||'',nin:x.nin||'',createdAt:new Date().toISOString()};a.push(u);localStorage.setItem(STORAGE_KEYS.USERS,JSON.stringify(a));setCurrentUserSession(u);getWalletBalance(u.id);return{success:true,user:u};}
function authenticateUser(email,password){const u=getRegisteredUsers().find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u)return{success:false,message:'Invalid email or password.'};setCurrentUserSession(u);getWalletBalance(u.id);return{success:true,user:u};}
function getCurrentUserSession(){const d=localStorage.getItem(STORAGE_KEYS.CURRENT_USER);return d?JSON.parse(d):null;}
function setCurrentUserSession(u){localStorage.setItem(STORAGE_KEYS.CURRENT_USER,JSON.stringify(u));}
function logoutUserSession(){localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);}
function getReports(){const d=localStorage.getItem(STORAGE_KEYS.REPORTS);return d?JSON.parse(d):[];}
function saveReport(r){const a=getReports();a.unshift(r);localStorage.setItem(STORAGE_KEYS.REPORTS,JSON.stringify(a));return r;}
function updateReport(id,updates){const a=getReports(),i=a.findIndex(r=>r.id===id);if(i<0)return{success:false,message:'Report not found.'};a[i]={...a[i],...updates,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEYS.REPORTS,JSON.stringify(a));return{success:true,report:a[i]};}
function getUserReports(uid){return getReports().filter(r=>r.userId===uid);}
